spring.application.name=talentforgeAI-backend
spring.mongodb.uri=${MONGO_URI}
cloudinary.cloud.name=${CLOUDINARY.CLOUD.NAME}
cloudinary.cloud.secret-key=${CLOUDINARY.CLOUD.API_SECRET}
cloudinary.cloud.api-key=${CLOUDINARY.CLOUD.API_KEY}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.password-reset-path=/auth/reset-password
app.frontend-url=${FRONTEND_URL}
app.email-verification-path=/auth/verify-email